services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=textile-marketplace-db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=yomenik'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'
