  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 15MB
    application:
      name: textile-marketplace-backend
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${MYSQL_ROOT_USERNAME}
      password: ${MYSQL_ROOT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
      database: mysql
  server:
    port: 8080
  logging:
    level:
      org:
        springframework:
          security: DEBUG